package database

import (
	"fmt"
	"log"
	"strings"

	"pos-system/backend/internal/models"

	"gorm.io/gorm"
)

// migrateProductLines backfills product_lines and splits legacy dual-inventory products into variants.
func migrateProductLines(db *gorm.DB) error {
	var products []models.Product
	if err := db.Where("product_line_id IS NULL OR product_line_id = 0").Find(&products).Error; err != nil {
		return err
	}

	for _, p := range products {
		line := models.ProductLine{
			Name:        p.Name,
			NameChinese: p.NameChinese,
			Category:    p.Category,
			ImageURL:    p.ImageURL,
			IsActive:    p.IsActive,
		}
		if err := db.Create(&line).Error; err != nil {
			return fmt.Errorf("create product line for product %d: %w", p.ID, err)
		}
		updates := map[string]interface{}{
			"product_line_id": line.ID,
			"variant_label":     clearGenericVariantLabel(p.VariantLabel),
		}
		if err := db.Model(&models.Product{}).Where("id = ?", p.ID).Updates(updates).Error; err != nil {
			return fmt.Errorf("link product %d to line %d: %w", p.ID, line.ID, err)
		}
	}

	var dualProducts []models.Product
	if err := db.Where("sell_by_qty = ? AND sell_by_weight = ?", true, true).Find(&dualProducts).Error; err != nil {
		return err
	}
	for _, p := range dualProducts {
		if err := splitDualProduct(db, p); err != nil {
			log.Printf("WARNING: split dual product %d: %v", p.ID, err)
		}
	}

	_ = db.Exec(`
		UPDATE products SET sell_by_qty = 1, sell_by_weight = 0, can_sell_by_weight = 0
		WHERE unit_type = 'quantity' AND sell_by_weight = 1
	`).Error
	_ = db.Exec(`
		UPDATE products SET sell_by_qty = 0, sell_by_weight = 1, unit_type = 'weight', can_sell_by_weight = 0
		WHERE unit_type = 'weight' OR (sell_by_weight = 1 AND sell_by_qty = 0)
	`).Error

	clearAutoGeneratedVariantLabels(db)
	return nil
}

// clearAutoGeneratedVariantLabels removes placeholder labels from the initial migration.
func clearAutoGeneratedVariantLabels(db *gorm.DB) {
	_ = db.Exec(`
		UPDATE products SET variant_label = ''
		WHERE LOWER(TRIM(variant_label)) IN ('standard', 'unit', 'weight')
	`).Error
}

func clearGenericVariantLabel(label string) string {
	switch strings.ToLower(strings.TrimSpace(label)) {
	case "standard", "unit", "weight", "":
		return ""
	default:
		return strings.TrimSpace(label)
	}
}

func splitDualProduct(db *gorm.DB, p models.Product) error {
	lineID := p.ProductLineID
	if lineID == 0 {
		return fmt.Errorf("product %d has no product_line_id", p.ID)
	}

	wtBarcode := strings.TrimSpace(p.WeightBarcode)
	if wtBarcode == "" {
		wtBarcode = strings.TrimSpace(p.Barcode)
	}
	if wtBarcode == "" {
		return fmt.Errorf("product %d has no weight barcode to split", p.ID)
	}

	if err := db.Model(&models.Product{}).Where("id = ?", p.ID).Updates(map[string]interface{}{
		"sell_by_weight":        false,
		"can_sell_by_weight":    false,
		"unit_type":             "quantity",
		"weight_barcode":        nil,
		"weight_barcode_prefix": "",
		"price_weight_g":        0,
		"prepack_weight_g":      0,
		"variant_label":         clearGenericVariantLabel(p.VariantLabel),
	}).Error; err != nil {
		return err
	}

	wtSKU := strings.TrimSpace(p.SKU)
	if wtSKU != "" {
		wtSKU = wtSKU + "-WT"
	}

	wtName := p.Name
	if !strings.Contains(strings.ToLower(wtName), "weight") {
		wtName = wtName + " (Weight)"
	}

	weightProduct := models.Product{
		ProductLineID:        lineID,
		Name:                 wtName,
		NameChinese:          p.NameChinese,
		SKU:                  wtSKU,
		Category:             p.Category,
		ImageURL:             p.ImageURL,
		VariantLabel:         "",
		UnitType:             "weight",
		SellByQty:            false,
		SellByWeight:         true,
		CanSellByWeight:      false,
		WeightBarcode:        wtBarcode,
		WeightBarcodePrefix:  p.WeightBarcodePrefix,
		PriceWeightG:         p.PriceWeightG,
		PrepackWeightG:       p.PrepackWeightG,
		WholesaleUnitsPerBox: p.WholesaleUnitsPerBox,
		IsActive:             p.IsActive,
	}
	if err := db.Create(&weightProduct).Error; err != nil {
		return err
	}

	var stocks []models.Stock
	if err := db.Where("product_id = ?", p.ID).Find(&stocks).Error; err != nil {
		return err
	}
	for _, s := range stocks {
		wtQty := s.WeightQuantityG
		if err := db.Model(&models.Stock{}).Where("id = ?", s.ID).Updates(map[string]interface{}{
			"weight_quantity_g": 0,
			"track_weight":      false,
		}).Error; err != nil {
			return err
		}
		if wtQty <= 0 && !s.TrackWeight {
			continue
		}
		wtStock := models.Stock{
			ProductID:         weightProduct.ID,
			StoreID:           s.StoreID,
			Quantity:          0,
			WeightQuantityG:   wtQty,
			TrackPrepacked:    false,
			TrackWeight:       true,
			LowStockThreshold: s.LowStockThreshold,
			LastUpdated:       s.LastUpdated,
		}
		if err := db.Where("product_id = ? AND store_id = ?", weightProduct.ID, s.StoreID).
			Assign(wtStock).FirstOrCreate(&wtStock).Error; err != nil {
			return err
		}
	}

	log.Printf("Split dual product %d → qty variant %d + weight variant %d (line %d)", p.ID, p.ID, weightProduct.ID, lineID)
	return nil
}
